import { Book, Review, UserProfile, ReadingStats } from './types';

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'The Quantum Garden',
    author: 'Elena Miranova',
    cover: '/books/quantum-garden.jpg',
    description: 'A mesmerizing tale of a botanist who discovers plants that exist in multiple dimensions. With stunning world-building and philosophical depth.',
    rating: 4.8,
    reviews: 3421,
    pages: 480,
    category: 'Science Fiction',
    progress: 65,
    currentPage: 312,
    addedDate: '2024-01-15',
    gradient: { from: '#A67C52', to: '#8B6F47' },
  },
  {
    id: '2',
    title: 'Shadows of Tomorrow',
    author: 'Marcus Chen',
    cover: '/books/shadows.jpg',
    description: 'A noir thriller following a detective through the neon-lit streets of a cyberpunk megacity, uncovering conspiracies that go deeper than time itself.',
    rating: 4.6,
    reviews: 2891,
    pages: 392,
    category: 'Mystery',
    progress: 42,
    currentPage: 165,
    addedDate: '2024-02-01',
    gradient: { from: '#7A5C3D', to: '#6B4C2F' },
  },
  {
    id: '3',
    title: 'The Gardener\'s Daughter',
    author: 'Sofia Rosetti',
    cover: '/books/gardener.jpg',
    description: 'Set in post-war Italy, a story of forbidden love, family secrets, and the healing power of nature. A sweeping historical romance.',
    rating: 4.9,
    reviews: 5023,
    pages: 528,
    category: 'Historical Romance',
    progress: 88,
    currentPage: 465,
    addedDate: '2023-11-20',
    gradient: { from: '#C4956C', to: '#A67C52' },
  },
  {
    id: '4',
    title: 'Echoes in the Void',
    author: 'James Whitmore',
    cover: '/books/echoes.jpg',
    description: 'An ambitious space opera exploring humanity\'s place in the universe. Epic scope with intimate character moments.',
    rating: 4.5,
    reviews: 2156,
    pages: 684,
    category: 'Science Fiction',
    progress: 23,
    currentPage: 157,
    addedDate: '2024-02-10',
    gradient: { from: '#6B4C2F', to: '#5A3D20' },
  },
  {
    id: '5',
    title: 'The Last Interview',
    author: 'David Hartley',
    cover: '/books/interview.jpg',
    description: 'A psychological thriller that unfolds entirely through interviews, unveiling a dark secret that connects five strangers.',
    rating: 4.7,
    reviews: 1893,
    pages: 312,
    category: 'Thriller',
    progress: 0,
    currentPage: 0,
    addedDate: '2024-02-15',
    gradient: { from: '#8B6F47', to: '#6B4C2F' },
  },
  {
    id: '6',
    title: 'Beneath the Canopy',
    author: 'Dr. Rebecca Santos',
    cover: '/books/canopy.jpg',
    description: 'A non-fiction exploration of the Amazon rainforest\'s ecosystem and the indigenous communities fighting for its survival.',
    rating: 4.4,
    reviews: 1567,
    pages: 432,
    category: 'Non-Fiction',
    progress: 34,
    currentPage: 147,
    addedDate: '2024-01-25',
    gradient: { from: '#A67C52', to: '#8B6F47' },
  },
  {
    id: '7',
    title: 'The Midnight Library',
    author: 'Nora James',
    cover: '/books/midnight.jpg',
    description: 'Between life and death exists a library where each book allows you to explore the life you could have lived. A magical tale of choices.',
    rating: 4.8,
    reviews: 4203,
    pages: 368,
    category: 'Contemporary Fiction',
    progress: 51,
    currentPage: 188,
    addedDate: '2023-12-08',
    gradient: { from: '#7A5C3D', to: '#6B4C2F' },
  },
  {
    id: '8',
    title: 'Crimson Tides',
    author: 'Isla Maritime',
    cover: '/books/tides.jpg',
    description: 'A nautical adventure following a pirate captain\'s daughter as she navigates treacherous seas and dangerous enemies.',
    rating: 4.6,
    reviews: 2234,
    pages: 456,
    category: 'Adventure',
    progress: 12,
    currentPage: 55,
    addedDate: '2024-02-03',
    gradient: { from: '#A67C52', to: '#936843' },
  },
  {
    id: '9',
    title: 'The Memory Keeper',
    author: 'Thomas Whitley',
    cover: '/books/memory.jpg',
    description: 'An elderly woman discovers she has the ability to store and retrieve memories. Her gift becomes both a blessing and a curse.',
    rating: 4.7,
    reviews: 3456,
    pages: 320,
    category: 'Fantasy',
    progress: 76,
    currentPage: 243,
    addedDate: '2024-01-10',
    gradient: { from: '#C4956C', to: '#A67C52' },
  },
  {
    id: '10',
    title: 'Lost Frequencies',
    author: 'Alex Patterson',
    cover: '/books/frequencies.jpg',
    description: 'A musician receives mysterious radio signals that seem to come from another dimension. A sci-fi mystery that blurs reality and fiction.',
    rating: 4.5,
    reviews: 1723,
    pages: 398,
    category: 'Science Fiction',
    progress: 39,
    currentPage: 155,
    addedDate: '2024-02-05',
    gradient: { from: '#8B6F47', to: '#7A5C3D' },
  },
  {
    id: '11',
    title: 'The Poet\'s Testament',
    author: 'Lady Catherine Holmes',
    cover: '/books/poet.jpg',
    description: 'A collection of interconnected poems and prose following a poet\'s journey through love, loss, and redemption.',
    rating: 4.6,
    reviews: 891,
    pages: 256,
    category: 'Poetry',
    progress: 100,
    currentPage: 256,
    addedDate: '2023-10-15',
    gradient: { from: '#6B4C2F', to: '#5A3D20' },
  },
  {
    id: '12',
    title: 'Tomorrow\'s Revolution',
    author: 'Professor Michael Zhang',
    cover: '/books/revolution.jpg',
    description: 'An exploration of how technology will reshape society in the next decade. Visionary and deeply researched.',
    rating: 4.3,
    reviews: 756,
    pages: 384,
    category: 'Non-Fiction',
    progress: 28,
    currentPage: 107,
    addedDate: '2024-02-12',
    gradient: { from: '#A67C52', to: '#8B6F47' },
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    author: 'Sarah Mitchell',
    rating: 5,
    text: 'Absolutely captivating! I couldn\'t put it down. The world-building is exquisite and the characters feel so real.',
    date: '2024-02-10',
    helpful: 342,
  },
  {
    id: '2',
    author: 'James Rivera',
    rating: 4,
    text: 'Great story with some pacing issues in the middle. Still highly recommend for sci-fi fans.',
    date: '2024-02-08',
    helpful: 156,
  },
  {
    id: '3',
    author: 'Elena Voss',
    rating: 5,
    text: 'Mind-bending concepts and beautiful prose. One of the best books I\'ve read this year.',
    date: '2024-02-05',
    helpful: 523,
  },
  {
    id: '4',
    author: 'Marcus Webb',
    rating: 4,
    text: 'Solid story. The ending felt a bit rushed, but the journey was worth it.',
    date: '2024-01-28',
    helpful: 89,
  },
  {
    id: '5',
    author: 'Nina Kovalski',
    rating: 5,
    text: 'This book changed how I think about consciousness and reality. Brilliant.',
    date: '2024-01-20',
    helpful: 678,
  },
];

export const mockReadingStats: ReadingStats = {
  totalBooks: 47,
  booksCompleted: 39,
  totalHours: 1245,
  currentStreak: 28,
  longestStreak: 45,
  thisWeekMinutes: 487,
  thisMonthMinutes: 1823,
  favoriteGenre: 'Science Fiction',
  averageRating: 4.6,
};

export const mockUserProfile: UserProfile = {
  id: 'user-1',
  name: 'Alex Reader',
  email: 'alex@novelgrab.app',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  joinDate: '2023-08-15',
  settings: {
    fontSize: 16,
    fontFamily: 'serif',
    lineHeight: 1.6,
    backgroundColor: 'cream',
    theme: 'light',
    autoScroll: false,
    scrollSpeed: 5,
  },
  stats: mockReadingStats,
  favoriteBooks: ['1', '3', '7', '9'],
  readingHistory: [
    { bookId: '1', date: '2024-02-15', duration: 45, pagesRead: 12 },
    { bookId: '3', date: '2024-02-15', duration: 60, pagesRead: 18 },
    { bookId: '7', date: '2024-02-14', duration: 38, pagesRead: 10 },
    { bookId: '9', date: '2024-02-14', duration: 52, pagesRead: 15 },
    { bookId: '1', date: '2024-02-13', duration: 41, pagesRead: 11 },
  ],
};

export const mockChapters = [
  {
    id: '1-1',
    number: 1,
    title: 'The Discovery',
    content: `The morning light filtered through the conservatory glass in fractured patterns, casting dancing shadows across Elena's workbench. She had been awake since four, though not by choice. The dreams had come again—vivid, intrusive, filled with colors that didn't exist in any spectrum she'd ever studied.

She set down her coffee, now cold, and turned her attention back to the seedling before her. The Heliantus variant she'd been cultivating for three months had finally shown signs of... something. She wasn't quite sure what to call it. In the traditional sense, the plant appeared normal—a genetic copy of its parent, growing predictably in its designated quadrant.

But there was something else. A presence, almost. A quantum signature that her instruments could barely register before it vanished. It was as if the plant existed and didn't exist simultaneously, flickering between states with each observation.

Elena adjusted her spectrometer, running the scan again. The readings were identical to yesterday: impossible. She had spent twenty years studying conventional biology, earned her doctorate in plant genetics, published seventeen papers on cellular regeneration. Nothing in her training had prepared her for what she was witnessing.

The plant seemed to pulse with an inner light that had no physical source.`,
    pageCount: 12,
    duration: 22,
  },
  {
    id: '1-2',
    number: 2,
    title: 'Quantum Resonance',
    content: `Her colleague, Dr. Rajesh Patel, wouldn't believe her. He barely believed her when she'd suggested that plants possessed some form of chemical communication system—something that had taken another three years to prove conclusively. No, she needed evidence first. Solid, reproducible, peer-reviewed evidence.

The oscilloscope hummed softly as it ran through its diagnostic cycle. Elena had repurposed equipment from the university's physics department, cobbling together an array of sensors that probably violated at least a dozen safety regulations. But regulations hadn't accounted for plants that bent spacetime.

A notification pinged on her tablet. Her 3 PM lecture was in thirty minutes. Botanical Genetics 301, taught to a lecture hall of disinterested graduate students who were only taking the course because it fulfilled their degree requirements. She should go. Instead, she pulled up the plant's genetic sequence and began scanning for anomalies.

If the physical manifestation matched its genetic blueprint perfectly, but its behavior defied physics, then something extraordinary was happening at the quantum level. Perhaps there was an explanation that didn't involve hallucinations or faulty equipment.

The plant's frond shifted, ever so slightly, toward her. It was growing. Changing. Becoming something entirely new.`,
    pageCount: 11,
    duration: 20,
  },
];

export const trendingBooks = [
  { ...mockBooks[0], trend: 1 },
  { ...mockBooks[2], trend: 2 },
  { ...mockBooks[3], trend: 3 },
  { ...mockBooks[6], trend: 4 },
  { ...mockBooks[4], trend: 5 },
];

export const recommendedBooks = [
  mockBooks[0],
  mockBooks[2],
  mockBooks[6],
  mockBooks[9],
  mockBooks[7],
  mockBooks[4],
];
